# Generated by Django 4.0.1 on 2022-06-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pro',
        ),
    ]
