# Generated by Django 4.0.1 on 2022-06-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='address',
        ),
    ]
