# Generated by Django 4.0.1 on 2022-07-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantitys',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
